name: biet
description: "BIET Student App Project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  percent_indicator: ^4.2.5
  curved_labeled_navigation_bar: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/

    # JSON Data
    - assets/data/

  #Fonts
  fonts:
    - family: AnekDevanagari
      fonts:
        - asset: assets/fonts/AnekDevanagari-Regular.ttf
          style: normal
    - family: AnekDevanagariCondensed
      fonts:
        - asset: assets/fonts/AnekDevanagari_SemiCondensed-Regular.ttf
