name: biet
description: "BIET Student App Project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  curved_labeled_navigation_bar: ^2.0.6
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/

    - .env

  #Fonts
  fonts:
    - family: AnekDevanagari
      fonts:
        - asset: assets/fonts/AnekDevanagari-Regular.ttf
          style: normal
    - family: AnekDevanagariCondensed
      fonts:
        - asset: assets/fonts/AnekDevanagari_SemiCondensed-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # IMPORTANT: Replace with your logo file path
  # min_sdk_android: 21 # Optional
